//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreintjeApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/TreinTijden")]
    [System.SerializableAttribute()]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((this.AliasField.Equals(value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Lat {
            get {
                return this.LatField;
            }
            set {
                if ((this.LatField.Equals(value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Long {
            get {
                return this.LongField;
            }
            set {
                if ((this.LongField.Equals(value) != true)) {
                    this.LongField = value;
                    this.RaisePropertyChanged("Long");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VertrektijdInfo", Namespace="http://schemas.datacontract.org/2004/07/TreinTijden")]
    [System.SerializableAttribute()]
    public partial class VertrektijdInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EindBestemmingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RitNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RouteTekstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TreinSoortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VertrekSpoorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> VertrekSpoorWijzigingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VertrekTijdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VertrekVertragingTekstField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EindBestemming {
            get {
                return this.EindBestemmingField;
            }
            set {
                if ((object.ReferenceEquals(this.EindBestemmingField, value) != true)) {
                    this.EindBestemmingField = value;
                    this.RaisePropertyChanged("EindBestemming");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RitNummer {
            get {
                return this.RitNummerField;
            }
            set {
                if ((this.RitNummerField.Equals(value) != true)) {
                    this.RitNummerField = value;
                    this.RaisePropertyChanged("RitNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteTekst {
            get {
                return this.RouteTekstField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteTekstField, value) != true)) {
                    this.RouteTekstField = value;
                    this.RaisePropertyChanged("RouteTekst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TreinSoort {
            get {
                return this.TreinSoortField;
            }
            set {
                if ((object.ReferenceEquals(this.TreinSoortField, value) != true)) {
                    this.TreinSoortField = value;
                    this.RaisePropertyChanged("TreinSoort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VertrekSpoor {
            get {
                return this.VertrekSpoorField;
            }
            set {
                if ((object.ReferenceEquals(this.VertrekSpoorField, value) != true)) {
                    this.VertrekSpoorField = value;
                    this.RaisePropertyChanged("VertrekSpoor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> VertrekSpoorWijziging {
            get {
                return this.VertrekSpoorWijzigingField;
            }
            set {
                if ((this.VertrekSpoorWijzigingField.Equals(value) != true)) {
                    this.VertrekSpoorWijzigingField = value;
                    this.RaisePropertyChanged("VertrekSpoorWijziging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VertrekTijd {
            get {
                return this.VertrekTijdField;
            }
            set {
                if ((this.VertrekTijdField.Equals(value) != true)) {
                    this.VertrekTijdField = value;
                    this.RaisePropertyChanged("VertrekTijd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VertrekVertragingTekst {
            get {
                return this.VertrekVertragingTekstField;
            }
            set {
                if ((object.ReferenceEquals(this.VertrekVertragingTekstField, value) != true)) {
                    this.VertrekVertragingTekstField = value;
                    this.RaisePropertyChanged("VertrekVertragingTekst");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITreintijden")]
    public interface ITreintijden {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreintijden/GetStations", ReplyAction="http://tempuri.org/ITreintijden/GetStationsResponse")]
        TreintjeApp.ServiceReference1.Station[] GetStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreintijden/GetStations", ReplyAction="http://tempuri.org/ITreintijden/GetStationsResponse")]
        System.Threading.Tasks.Task<TreintjeApp.ServiceReference1.Station[]> GetStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreintijden/GetVertrektijden", ReplyAction="http://tempuri.org/ITreintijden/GetVertrektijdenResponse")]
        TreintjeApp.ServiceReference1.VertrektijdInfo[] GetVertrektijden(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITreintijden/GetVertrektijden", ReplyAction="http://tempuri.org/ITreintijden/GetVertrektijdenResponse")]
        System.Threading.Tasks.Task<TreintjeApp.ServiceReference1.VertrektijdInfo[]> GetVertrektijdenAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITreintijdenChannel : TreintjeApp.ServiceReference1.ITreintijden, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TreintijdenClient : System.ServiceModel.ClientBase<TreintjeApp.ServiceReference1.ITreintijden>, TreintjeApp.ServiceReference1.ITreintijden {
        
        public TreintijdenClient() {
        }
        
        public TreintijdenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TreintijdenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TreintijdenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TreintijdenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TreintjeApp.ServiceReference1.Station[] GetStations() {
            return base.Channel.GetStations();
        }
        
        public System.Threading.Tasks.Task<TreintjeApp.ServiceReference1.Station[]> GetStationsAsync() {
            return base.Channel.GetStationsAsync();
        }
        
        public TreintjeApp.ServiceReference1.VertrektijdInfo[] GetVertrektijden(string id) {
            return base.Channel.GetVertrektijden(id);
        }
        
        public System.Threading.Tasks.Task<TreintjeApp.ServiceReference1.VertrektijdInfo[]> GetVertrektijdenAsync(string id) {
            return base.Channel.GetVertrektijdenAsync(id);
        }
    }
}
